export const CORS_ENABLED = 'CORS_ENABLED';
export const CORS_HEADERS = 'CORS_HEADERS';
export const CORS_ORIGINS = 'CORS_ORIGINS';
export const TEMPLATE_BUCKET_NAME = 'TEMPLATE_BUCKET_NAME';
export const SNS_TOPIC_ARN = 'SNS_TOPIC_ARN';
export const RECAPTCHA_ENABLED = 'RECAPTCHA_ENABLED';
export const RECAPTCHA_SECRET_KEY = 'RECAPTCHA_SECRET_KEY';
export const SECRET_ID = 'SECRET_ID';
