name: CI

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure Node
      uses: actions/setup-node@v3
      with:
        cache: "yarn"
        node-version: '14'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run:  yarn build
      env:
        NX_BRANCH: ${{ github.ref_name }}
