name: Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CI Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "14"

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          NX_BRANCH: ${{ github.ref_name }}

      - name: Release
        run: npx lerna version --conventional-commits --create-release github --yes
        env:
          NX_BRANCH: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: npx lerna publish from-package --yes
        env:
          NX_BRANCH: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
